accounts/urls.py
from django.urls import path
from .views import MyPageView, AccountNameChangeView

app_name = "accounts"

urlpatterns = [
    path("mypage/", MyPageView.as_view(), name="mypage"),
    path("name/", AccountNameChangeView.as_view(), name="name_change"),
]

myapp/urls.py
from django.urls import path
from myapp.views.playground_views import PlaygroundListView
from myapp.views.favorite_views import (
    AddFavoriteView,
    RemoveFavoriteView,
    FavoriteListView,
)
from myapp.views.review_views import AddReviewView, ReviewListView
from myapp.views.ranking_views import RankingListView
from myapp.views.detail_views import FacilityDetailView
from myapp.views.about import about_view
import myapp.views as views  # viewsモジュールをインポート


app_name = "myapp"

urlpatterns = [
    path("", PlaygroundListView.as_view(), name="index"),
    path("facilities/<int:pk>/", FacilityDetailView.as_view(), name="facility_detail"),
    path("ranking/", RankingListView.as_view(), name="ranking"),
    path("favorites/", FavoriteListView.as_view(), name="favorites"),
    path("add_favorite/", AddFavoriteView.as_view(), name="add_favorite"),
    path("remove_favorite/", RemoveFavoriteView.as_view(), name="remove_favorite"),
    path(
        "playground/<int:playground_id>/add_review/",
        AddReviewView.as_view(),
        name="add_review",
    ),
    path(
        "playground/<int:playground_id>/reviews/",
        ReviewListView.as_view(),
        name="view_reviews",
    ),
    path(
        "playground/<int:pk>/review/create/",
        views.ReviewCreateView.as_view(),
        name="review_create",
    ),
    path("about/", about_view, name="about"),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from users.forms import AccountNameForm


class MyPageView(LoginRequiredMixin, View):
    template_name = "accounts/mypage.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)


class AccountNameChangeView(LoginRequiredMixin, View):
    template_name = "accounts/account_name_change.html"
    success_url = reverse_lazy("accounts:mypage")

    def get(self, request, *args, **kwargs):
        form = AccountNameForm(instance=request.user)
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        form = AccountNameForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect(self.success_url)
        return render(request, self.template_name, {"form": form})

accounts/templates/accounts/_left_menu.html
<div class="list-group">
    <a href="{% url 'accounts:mypage' %}" class="list-group-item list-group-item-action {% if request.path == '/accounts/mypage/' %}active{% endif %}">マイページ</a>
    <a href="{% url 'accounts:name_change' %}" class="list-group-item list-group-item-action {% if request.path == '/accounts/name/' %}active{% endif %}">アカウント名の変更</a>
    <a href="{% url 'account_email' %}" class="list-group-item list-group-item-action {% if request.path == '/accounts/email/' %}active{% endif %}">メールアドレスの管理</a>
    <a href="{% url 'account_change_password' %}" class="list-group-item list-group-item-action {% if request.path == '/accounts/password/change/' %}active{% endif %}">パスワードの変更</a>
</div>

accounts/templates/accounts/account_name_change.html
{% extends "base.html" %}

{% block title %}アカウント名の変更{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-3">
        {% include "accounts/_left_menu.html" %}
    </div>
    <div class="col-md-9">
        <h1 class="my-4">アカウント名の変更</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">更新</button>
        </form>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/mypage.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}マイページ{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-3">
        {% include "accounts/_left_menu.html" %}
    </div>
    <div class="col-md-9">
        <h1 class="my-4">マイページ</h1>
        <p>ようこそ、{{ user.account_name }}さん！</p>
        <p>左側のメニューから、各機能にアクセスしてください。</p>
    </div>
</div>
{% endblock %}